services:
  nginx:
    image: nginx:alpine
    container_name: hospital-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: hospital-frontend
    expose:
      - "80"
    restart: always

  backend:
    build:
      context: ./backend
    container_name: hospital-backend
    expose:
      - "8000"
    restart: unless-stopped
